try:
    print(1)
    prin
except Exception as e:
    print(2)
    exit(1)
finally:
    print(3)

print(4)
